### ISSUE TITLE
Do you want me to improve GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [jugla/worldtidesinfocustom#1]
If you want, I can add some advanced CI to your repo.
Let me know if you want a PR.
- Do you want to enable auto-formatting whenever pushed?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by jugla** [comment]
Hello
What do you mean by "packaged or independent" ? (perhaps it's obvious, but I've just started with github)

**Comment by KTibow** [comment]
It's basically the difference between putting the CI in a separate GitHub repository and putting all of the code in the Ci here.

**Comment by jugla** [comment]
ok , let's try with your preferred method !
Please perform a PR so that , I can accept it.
Thanks in advance
Philippe
