### ISSUE TITLE
Hide Tides Sensor from Map

### ISSUE THREAD

**Issue by ChrisRomp** [jugla/worldtidesinfocustom#11]
**Is your feature request related to a problem? Please describe.**
The tides sensor is showing on the Home Assistant map. It's not necessary and adds clutter.

**Describe the solution you'd like**
It would be great to have a way to disable the sensor entity from showing on the map.  A good example of a component that has this as a toggle is the AirVisual component.

**Describe alternatives you've considered**
I looked for ways to have HA hide entities on the map or for a configuration option for this component, but I don't see one. If I've missed it please let me know. :)

**Additional context**
n/a

**Comment by jugla** [comment]
Hello,
Within the configuration option in integration menu , you can disable or enable the display on map (per worldtides location).

Hereafter some snapshot (in french) : click within the yellow circle to go in the menu : 
![image](https://user-images.githubusercontent.com/59493499/124830832-bcb64c80-df7a-11eb-91c2-3132bc878de3.png)
![image](https://user-images.githubusercontent.com/59493499/124830953-e2dbec80-df7a-11eb-810e-e00f9622b254.png)
![image](https://user-images.githubusercontent.com/59493499/124831055-06069c00-df7b-11eb-8456-7cd27c605ec0.png)
![image](https://user-images.githubusercontent.com/59493499/124831151-20407a00-df7b-11eb-9c89-91db06095ace.png)

Tell me if it helps

Philippe

**Comment by ChrisRomp** [comment]
Ah, I didn't configure mine in the GUI. I'll update it and try that route.
Thanks.

**Comment by ChrisRomp** [comment]
I'm won't be able to reconfigure it 'til sometime later, so I'll close this and revisit it if I can't get it working. Thanks again!
