### ISSUE TITLE
How to change parameters in UI installation mode?

### ISSUE THREAD

**Issue by sbussinger** [jugla/worldtidesinfocustom#12]
I installed integration from HACS and then added integration via UI. How do I change parameters now that it's installed? For that matter, how do you set additional parameters during installation (e.g. I need to change "vertical_ref", but that's not one of the entry fields while adding the integration)?

When I click on "Configure" for the integration, it only has one setting which is "Show monitored tides on the map".

**Comment by jugla** [comment]
Hello,
Indeed, when I've implemented UI, I've done something similar to _configuration.yaml_ .
With configuration.yaml, we cannot change parameters without "reboot".
I will see, how to perform some enhancement to change parameter without re-install the integration via UI.
Nevertheless, I think no all parameter can be changed online.

**Comment by sbussinger** [comment]
Thanks @jugla

Your documentation says the UI method is recommended, but I had much difficulty getting the UI method to install and then couldn't find a way to change any of the documented parameters (it's important in my case to set vertical_ref to CD). I switched to configuration.yaml after that and was able to get it working. But if you're going to recommend UI configuration, it really needs to support adjusting all the parameters.

**Comment by jugla** [comment]
Indeed I migrate configuration.yaml to UI.
In fact in UI, you have 2 kind of definition upon creation of worldtidesinfo integration : 
![image](https://user-images.githubusercontent.com/59493499/129626710-e58b3fff-b804-4427-85b0-02166dc13088.png)
You can then select the "expert definition" : 
![image](https://user-images.githubusercontent.com/59493499/129626803-3fff7537-16b6-40ff-9b71-686aa6ea0a05.png)

Then you can select the vertical ref you want i.e. CD : 
![image](https://user-images.githubusercontent.com/59493499/129627117-554f2a97-4b35-4ed7-aaef-b147ed31b191.png)


Tell me if it answers to your issue.

I keep idea of changing some parameters in online way.

**Comment by sbussinger** [comment]
Is there anyway to get to that UI after the integration has already been added? In other words can you change an existing integration using that UI or is it only available for initial creation. I think that's where I got confused. Thanks!

**Comment by jugla** [comment]
Hello,
Thanks for your reply.
Currently , UI has all parameters for creation.
With your issue/question, I will see how to improve UI in order to change parameter once the integration has been created !

Wait a little  ;-)

**Comment by jugla** [comment]
Please go to V7.0.0 : I have added some options.

I close this issue as options are available.
I will put more option on next release.
