### ISSUE TITLE
Transparent background for tide chart images?

### ISSUE THREAD

**Issue by wheindl** [jugla/worldtidesinfocustom#16]
I love this application and use it to view tide charts for six different favorite locations; but would love to see the tide chart images have transparent (rather than white) backgrounds.  I place these in a vertical stack-in-card with an entities card showing specific sensor values.  The entities card takes the background shading of my Lovelace theme; but the tide chart is a straight white background.  
![Image1](https://user-images.githubusercontent.com/5498728/161403558-defb1148-0c0d-46a1-8a8a-e9328d308b7f.jpg)

**Comment by jugla** [comment]
Thanks for your feed back !
I'll take the idea. I will see how to do it

**Comment by jugla** [comment]
Ok , matplotlib.pyplot.savefig allows to have transparentbool option.

**Comment by jugla** [comment]
Hello,
I have added transparent option .
You can access through UI.
Available in v11.2.0.
Please can you send me a feed back. Thanks in advance.

**Comment by wheindl** [comment]
![tide-screen-shot](https://user-images.githubusercontent.com/5498728/162550289-03e3431f-fcb5-4b7d-8979-4803410d7eeb.jpg)

Here you go.  It looks good.  The top image is with transparency set; the bottom image is with transparency not set.  I did have to adjust the settings in my theme to make this work (as with other integrations with transparent images).  It will probably help to point this out: it helps to know how to edit themes.  

Thank you for implementing this!

**Comment by jugla** [comment]
Hello,
Thanks !
I have updated [https://github.com/jugla/worldtidesinfocustom](https://github.com/jugla/worldtidesinfocustom) to add information.

Don't hesitate to propose improvment ;-)
