### ISSUE TITLE
Platform error sensor.worldtidesinfocustom - numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by wildoracle** [jugla/worldtidesinfocustom#18]
**Describe the bug**
The system cannot restart because the configuration is not valid: Platform error sensor.worldtidesinfocustom - numpy.core.multiarray failed to import

**To Reproduce**
1. Go to 'Settings>System'
2. Click on 'Restart'

**Expected behavior**
No errors, allowing me to restart

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.worldtidesinfocustom - numpy.core.multiarray failed to import

**Comment by jugla** [comment]
Hello,
It seems to be related to numpy library.
- Please, which installation do you have : core, .... ?
- Have you numpy manually installed ?

Thanks in advance

**Comment by wildoracle** [comment]
Hi, sorry I didn't include my specs in the original post. Here you go:
Home Assistant Core 2022.5.0
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.108
Agent version 1.2.1

I have not manually installed numpy so it's probably part of the HA core? I'm guessing numpy is a variant of python?

**Comment by PictureMil** [comment]
Hi. Same problem here after upgrading to 2022.5. The camera sensors get created, but all the statistical sensors are gone because of the numpy error.

**Comment by Automot360** [comment]
Hi, first of all thank for your work on the Tide Plugin.
I’ am using Home Assistant VM on Synology, results in no manual numpy installation.
I hope that helps, let me know if I can help with something else.

**Comment by wildoracle** [comment]
I'm also running HA on the VM in Synology in case that helps. The rest of my config info is above. Thanks!

**Comment by jugla** [comment]
Thanks all for your feed back.
It seems to be related to the configuration on synology.
NB: on my raspberry pi 4, with HA 2022.5 it works.

**Comment by jugla** [comment]
Just a try, in your homeassistant directory (e.g. `/home/homeassistant/.homeassistant`) , can you mofify this file : 
`~/.homeassistant/custom_components/worldtidesinfocustom/manifest.json`
change 
`"requirements": ["matplotlib>=3.4.2","pyworldtidesinfo==2.1.0"],` 
into `"requirements": ["matplotlib>=3.5.0","pyworldtidesinfo==2.1.0"],`
The issue is that I don't call numpy directly

**Comment by jugla** [comment]
In component called by HA 2022.5, the numpy version is 1.21.4.
Another guess in the previous file, change : 
`"requirements": ["matplotlib>=3.4.2","pyworldtidesinfo==2.1.0"],`
into
`"requirements": ["numpy==1.21.4","matplotlib>=3.4.2","pyworldtidesinfo==2.1.0"],`

**Comment by jugla** [comment]
Please can you give me your feed back ?

**Comment by jugla** [comment]
NB1 : numpy is a package to perform numeric computation cf. [https://numpy.org/](https://numpy.org/)
NB2 : py3-numpy is build package [https://pkgs.alpinelinux.org/package/edge/community/x86/py3-numpy](https://pkgs.alpinelinux.org/package/edge/community/x86/py3-numpy) to get numpy

**Comment by cyrenaud** [comment]
> "requirements": ["numpy==1.21.4","matplotlib>=3.4.2","pyworldtidesinfo==2.1.0"],

Tried this without any luck.

Running on QNAP Virtualisation Station with:
Home Assistant Core 2022.5.1
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.108

**Comment by PictureMil** [comment]
Yep, same for me. No joy with those tweaks.

Version:	core-2022.5.1
Installation Type:	Home Assistant OS
Development:	false
Supervisor:	true
Docker:	true
User:	root
Virtual Environment:	false
Python Version:	3.9.9
Operating System Family:	Linux
Operating System Version:	5.10.108
CPU Architecture:	x86_64

**Comment by PictureMil** [comment]
I should declare that I am still runing a yaml config for this integration. I probably missed any notifications that were published when a UI config became available. That said; in order to find a fix I have tried deleting the integration and reinstalling with UI config. It still does not work. Anyway, thought I should mention this in case there were any specific steps that a user should take when moving from YAML to UI. Thanks!

**Comment by jugla** [comment]
Is there anyone with the issue, can, in configuration.yaml, set a trend sensor [https://www.home-assistant.io/integrations/trend/](https://www.home-assistant.io/integrations/trend/) on whatever.
The aim is to see if you have or not the same issue with a component from HA .
Wacht out in 2022.5.1 the nump version has been changed into 1.21.6 .

**Comment by jugla** [comment]
Question have you been to this page [https://www.pythonpool.com/solved-importerror-numpy-core-multiarray-failed-to-import/](https://www.pythonpool.com/solved-importerror-numpy-core-multiarray-failed-to-import/) ?

**Comment by wildoracle** [comment]
> 

In my /config/binary_sensor.yaml file, should I set up my YAML like this?
`  - platform: trend
    sensors:
      worldtidesinfo:
        entity_id: sensor.worldtidesinfo`

**Comment by jugla** [comment]
Hello,
There are some *carriage return* ;-)
```yaml
# Example configuration.yaml entry
binary_sensor:
  - platform: trend
    sensors:
      cpu_speed:
        entity_id: sensor.cpu_speed
```

Please use another sensor like `sensor.hacs`

**Comment by wildoracle** [comment]
> 

If I were to follow this guide, would I be trying it in the command line within Synology's VM software (where the input cursor is `ha >`) ? or within the SSH & Web Terminal add-on UI?

**Comment by wildoracle** [comment]
> Hello, There are some _carriage return_ ;-)
> 
> ```yaml
> # Example configuration.yaml entry
> binary_sensor:
>   - platform: trend
>     sensors:
>       cpu_speed:
>         entity_id: sensor.cpu_speed
> ```
> 
> Please use another sensor like `sensor.hacs`

Oh, yes - it didn't include the carriage returns when I pasted here. :) 
As for the content of the YAML, I want to monitor sensor.hacs? 
`  - platform: trend
    sensors:
      hacs:
        entity_id: sensor.hacs`

**Comment by jugla** [comment]
don't forget the `binary_sensor`

**Comment by jugla** [comment]
Before modifying configuration.yaml, make a backup of this file

**Comment by wildoracle** [comment]
yes, I have my YAML separated out into a /config/binary_sensor.yaml file

But... I have to comment out the worldtidesinfo lines from my sensor.yaml in order to restart. Will that negate the test?

**Comment by jugla** [comment]
You can leave worldtidesinfo or comment it out. As you want

**Comment by wildoracle** [comment]
> Is there anyone with the issue, can, in configuration.yaml, set a trend sensor https://www.home-assistant.io/integrations/trend/ on whatever ? The aim is to see if you have or not the same issue with a component from HA . Wacht out in 2022.5.1 the nump version has been changed into 1.21.6 .

OK, I've restarted with the new `trend` yaml in my binary_sensor.yaml file... what am I needing to look for now?

**Comment by jugla** [comment]
Do see the sensor , you have created ?

**Comment by jugla** [comment]
In the log, I would like to know if you have the same trace `numpy.core.multiarray failed to import`

**Comment by wildoracle** [comment]
> 

Pardon my ignorance, but I don't know what the name of the sensor would be but I have this in my logs:
Logger: homeassistant.components.binary_sensor
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Binary sensor (documentation, issues)
First occurred: 11:12:43 AM (2 occurrences)
Last logged: 11:12:43 AM

Setup of binary_sensor platform trend is taking over 10 seconds.
Setup of binary_sensor platform hassio is taking over 10 seconds.

**Comment by jugla** [comment]
Thanks a lot @wildoracle 
It seems we are falling on issue https://github.com/home-assistant/core/issues/71270
Seems to be solved on HA 2022.5.2

**Comment by jugla** [comment]
HA 2022.5.2 has been released. The issue is there ?

**Comment by PictureMil** [comment]
Must be pleasing to know it wasn't your code from your brilliant integration! 2022.05.2 hasn't arrived for me yet. Thank you!

**Comment by jugla** [comment]
:-)

**Comment by PictureMil** [comment]
A system reboot triggered the new release being on offer. Confirming 2022.05.2 with its rebuilt numpy wheels has fixed this error. May the tides rise and fall!

Nice!

**Comment by wildoracle** [comment]
THANK YOU for this HACS addon, and for being so helpful! I can also confirm that 2022.5.2 fixed the issue for me.

**Comment by jugla** [comment]
Thanks all for your feed back
