### ISSUE TITLE
Images aren't 'showing'

### ISSUE THREAD

**Issue by MrMxyzptlk** [jugla/worldtidesinfocustom#19]
Latest version of HA on HA Blue!
Latest version of WorldTidesCustom installed from HACS.
The integration is working well, but the 3 images just show a placeholder for a preview, and shows idle at the bottom of the image window?

**Comment by jugla** [comment]
Hello,
Please can you show a screenshot/snapshot ?
Idle has no meaning here since for HA, the camera is quite static ;-)

Is it possible to check if : 
- in the directory where `configuration.yaml` is, you have a directory `www`.
- in this directory `www`, you have some pictures 

Thanks in advance

**Comment by MrMxyzptlk** [comment]
![Screenshot 2022-12-09 at 4 49 21 PM](https://user-images.githubusercontent.com/1753001/206801548-d66bd862-503c-4d75-b178-08a640a50674.png)
![Screenshot 2022-12-09 at 4 48 51 PM](https://user-images.githubusercontent.com/1753001/206801553-2a8dc086-2c2c-4bff-8dec-e7359ddb8218.png)


Yes www is in the root with configuration.yaml

3 pictures but not the 3 trying to be shown in the screenshot

**Comment by jugla** [comment]
Sounds good.
Please can you make a try. Can you declare "Fripp_Inlet" instead of "Fripp Inlet".
I wonder if the "space" makes strange behaviour.

In the `home-assistant.log` (at same place of `configuration.yaml`) , can you see if you have a sentence like "Could not read camera XXX image from file: XXX" (it's a warning message created by the integration)

Thanks in advance

**Comment by MrMxyzptlk** [comment]
I added a new instance called 'Fripp', and deleted 'Fripp Inlet'; that made no difference.
There is not an error message in the logs.
I have verified all 3 pictures are in the www directory and when I open the images they are correct.
They just don't display on my dashboards?

**Comment by jugla** [comment]
Hello,
Please, can you modify your  `configuration.yam` with : 
```
logger:
  logs:
    custom_components.worldtidesinfocustom: debug
```
To see trace when integration attempt to read camera files.
Thanks in advance
Philippe

**Comment by MrMxyzptlk** [comment]
I added to the config and restarted HA.

I still don't see any errors in the 'logbook'.

![Screenshot 2022-12-11 at 11 58 59 AM](https://user-images.githubusercontent.com/1753001/206917547-48af98c6-b9ff-4a04-9c52-974d561f716a.png)

**Comment by jugla** [comment]
Hello,
Great you have the picture !

**Comment by MrMxyzptlk** [comment]
No, I've always had the entity picture; it doesn't ever show on the 'card'.

**Comment by jugla** [comment]
You add something like this in the card (modify the last line) : 
```
show_state: true
show_name: true
camera_view: auto
type: picture-entity
image: https://demo.home-assistant.io/stub_config/bedroom.png
entity: camera.royan_tides_long_plot_picture
```

**Comment by MrMxyzptlk** [comment]
I never created the card, it was added automatically.
I will try that.

However even though the images show in the Integration, if I go directly to the entity you can see the same issue.
![Screenshot 2022-12-11 at 12 10 14 PM](https://user-images.githubusercontent.com/1753001/206918149-ab875b6e-cbb0-404f-98a6-71eae30bfb2c.png)
![Screenshot 2022-12-11 at 12 10 06 PM](https://user-images.githubusercontent.com/1753001/206918150-f0708dd2-6155-44da-9689-b3d02af0cbe1.png)

**Comment by jugla** [comment]
Via menu, add "image entity", in camera, select one of suggested camera "Fripp_curve_xxx"

**Comment by jugla** [comment]
Tell me, I think you are close to the target !!

**Comment by MrMxyzptlk** [comment]
So I left the 3 auto created picture cards, and added a 4th pointing to /local/www/Fripp.png
If I double click on this file it opens just fine.

![Screenshot 2022-12-11 at 12 23 15 PM](https://user-images.githubusercontent.com/1753001/206918767-3cbbaf63-d7f1-4eda-ab0c-ad148ff7706b.png)

**Comment by jugla** [comment]
Please can you give me in text format, the card, you have entered ?

**Comment by MrMxyzptlk** [comment]
I did a new install and a reboot, so no cards. The entity cards for the pics still have the same issue.
![image](https://user-images.githubusercontent.com/1753001/206924468-25eee7eb-a45d-43b2-a99e-90f8f70cbf39.png)

**Comment by jugla** [comment]
Hello,
In dashboard, please can you send me the configuration you have made to display the camera ?
On the card, do as if, you want to modify it and ask to see the configuration in text format.

**Comment by MrMxyzptlk** [comment]
I no longer have any dashboard cards setup for this.

As you see above, the device / integration is all fine; except when I open the entities for the 3 pictures...they all show 'preview' and no picture only a textual reply. "Preview of the Fripp ********* camera".

I'm not going to spend any time setting up cards until I can get the Integration fully functional.

**Comment by jugla** [comment]
Hello,
If you this : 
![image](https://user-images.githubusercontent.com/59493499/207053325-6a542c55-04ba-4e0a-b71c-69c2e06c9c19.png)
it means it works :-)

Here's mine :  
![image](https://user-images.githubusercontent.com/59493499/207053581-484da655-c8ec-422f-a77c-0c65aaf42048.png)

If you just add to entity via `add to dashboard`, normally it shall work
![image](https://user-images.githubusercontent.com/59493499/207054134-fc70ec1c-3af2-4c8e-ad3d-c428a7da490a.png)

**Comment by MrMxyzptlk** [comment]
I know, mine are the same way, but try clicking on one of picture entities; for me it doesn't show the picture, I only see the thumbnails exactly like you are showing above.

**Comment by MrMxyzptlk** [comment]
I don't know if this is a HA issue or the Integration.
I'm running HA Blue! with the latest updates.

**Comment by MrMxyzptlk** [comment]
Thank you for the clarification.
