### ISSUE TITLE
 Credits used incorrect?

### ISSUE THREAD

**Issue by realjax** [jugla/worldtidesinfocustom#21]
**Describe the bug**
Documentation says credits used per day is 3 but when I look at the last 10 calls it shows a call is made every 60 minutes. Which equates to 24 call per day..

**To Reproduce**
1. Go to [https://www.worldtides.info/overview](https://www.worldtides.info/overview)
2. check 'last 10 apicalls'

see screenshot

**Expected behavior**
3 credits used per day, not 24

**Screenshots**
![Screenshot 2023-02-23 at 13 25 04](https://user-images.githubusercontent.com/883435/220917035-108ae46e-0150-4d02-8908-dbb3521095b1.png)

**Comment by jugla** [comment]
Hello
Thanks for your feed back.
Please can you give me your configuration?
I mean static place or moving. Is it the first day ?
Thanks in advance.

**Comment by realjax** [comment]
I'm not sure what you mean by static place or moving. I have an HA instance in my house setup that doesnt go anywhere. Does that answer your question?
It is not the first day, it does an update exactly every hour.
configuration is this 
 
![Screenshot 2023-02-24 at 10 43 39](https://user-images.githubusercontent.com/883435/221146260-e1f3ba78-74ea-4135-9737-6b48c06b40cc.png)

**Comment by realjax** [comment]
Just realised I might be caused by the fact that I also have this one configured: https://www.home-assistant.io/integrations/worldtidesinfo  !

I will remove that one and then let you know if that was it

**Comment by jugla** [comment]
Hello,
Thanks a lot for the reply.
In the HA worldtidesinfo, there is a request every hour.
There is no optimization.
`SCAN_INTERVAL = timedelta(seconds=3600)` in file `core/homeassistant/components/worldtidesinfo/sensor.py`

**Comment by jugla** [comment]
> I'm not sure what you mean by static place or moving. I have an HA instance in my house setup that doesnt go anywhere. Does that answer your question?

When you have defined the tide location, you can refer to a _static point_ (by default your home location) or attach to a tracker (i.e. a boat GPS) (i.e. _moving_)

**Comment by realjax** [comment]
Yep, the HA worldtidesinfo was causing it!  Thanks for your help and I will close to his now.
