### ISSUE TITLE
With HA 2023.4 Failed to validate CalendarEvent: Expected all values to have a timezone

### ISSUE THREAD

**Issue by Canonfodda** [jugla/worldtidesinfocustom#23]
**Describe the bug**
Version installed currently is V12.3.1
Pre 2023.4 the calendar entries were working as described with upto 2 High tides and 2 low tides being added to the calendar,
all other functions of the worldtidesinfocustom are working as stated and as configured from the UI only. (no yaml configurations made).

Settings -> Systems -> Logs has an error of:

Logger: homeassistant.helpers.entity
Source: components/calendar/__init__.py:353 
First occurred: April 16, 2023 at 2:41:16 PM (356 occurrences) 
Last logged: 12:41:26 PM
```
Update for calendar.stoney_point_tides fails
Update for calendar.stony_point_pier fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 89, in validate
    raise vol.Invalid("Expected all values to have a timezone")
voluptuous.error.Invalid: Expected all values to have a timezone
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 351, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected all values to have a timezone
```
The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/worldtidesinfocustom/calendar.py", line 272, in async_update
    event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 353, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected all values to have a timezone
```

**To Reproduce**
1. Add a HA Calendar and confirm you can add event to this calendar. 
2. Install from HACS worldtidesinfocustom.
3. reboot HA
4. Obtain a pre-paid API key.
5. Goto Settings -> Devices & Services.  Add worldtidesinfocustom
6. Configure using the UI 
7. Determine that data is being returned from the Tides service and the API is working.
8. Attempt to see events in the HA Calendar for the Tide entity you have configured. 
9. Error is displayed in the calendar. "Could not retrieve events for calendars: Stoney Point Tides".    

**Expected behavior**
As it was described on Github page.

**Screenshots**
Error message on HA Calendar screen:
<img width="472" alt="Screenshot 2023-04-16 at 15 10 29" src="https://user-images.githubusercontent.com/55517490/232272396-5e245b3c-3cb1-4977-a778-bb798fc29f49.png">

Image of Entity screen and sensors.
<img width="1748" alt="Screenshot 2023-04-16 at 15 20 46" src="https://user-images.githubusercontent.com/55517490/232272659-986af4b8-b85b-42f2-b513-ade9b0abc23f.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. macOS 13.2.1 (22D68)
 - Browser: Safari
 - Version [e.g. 22]. Version 16.3 (18614.4.6.1.6)  

**Smartphone (please complete the following information):**

**Additional context**

I am in the Southern Hemisphere, and worldtidesinfocustom was installed when we were in (AEDT) UTC+11 timezone, were are now in (AEST) UTC+10.

Reloaded the V12.3.1 with HA 2023.4.4 and rebooted. 
Did not remove image only reloaded it so none of the .storage configs would have been altered.
Added a second instance of worldtidesinfocustom with a different tidal point but still same error with calendar.

Running on:
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest
Running on a  Raspberry Pi 3 

Anythings I can add, I am happy to provide. 
See also Github:  https://github.com/Antoni-Czaplicki/vulcan-for-hassio/issues/42  as it would seem to similar problem for HA calendar.

**Comment by jugla** [comment]
Thanks a lot for your well described issue.
I will see if on my side , I got the same thing in order to see how to solve it.

**Comment by Canonfodda** [comment]
Updated only,  world tide info custom : 12.3.2 on Home Assistant 2023.4.4

Settings -> Systems -> Logs  reported No errors for 12.3.2 

Enabled calendar entries for 12.3.2 tides: Information is now being reported in calendar with out error.
Confirmed Tide times aligned in Calendar and in information reported in cameras _plot_picture and _long_plot_picture

example of calendar attached 
<img width="1623" alt="Screenshot 2023-04-18 at 08 57 39" src="https://user-images.githubusercontent.com/55517490/232627965-ba55e01b-e505-4be3-8787-0afd42f739f4.png">

I would say this issue is resolved with my thanks for the great work.
Please close unless there is more that you would like me to test, report, provide feedback on.

Cheers & G'day to you.

**Comment by jugla** [comment]
Thanks a lot @Canonfodda 
Have good week end
