### ISSUE TITLE
Deprecated calls (Will not work anymore in HA Core 2025.1)

### ISSUE THREAD

**Issue by KlaraJa** [jugla/worldtidesinfocustom#25]
Hi,

today I noticed that HA is throwing warnings that some calls from this integration are deprecated and need to be replaced by the new ones.

This is the warning log from HA Core:

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 21:22:28 (13 occurrences)
Last logged: 21:23:57

LENGTH_FEET was used from worldtidesinfocustom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.FEET instead, please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues
LENGTH_KILOMETERS was used from worldtidesinfocustom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues
LENGTH_METERS was used from worldtidesinfocustom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues
LENGTH_MILES was used from worldtidesinfocustom, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/jugla/worldtidesinfocustom/issues
DEVICE_CLASS_TIMESTAMP was used from stadtreinigung_hamburg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TIMESTAMP instead, please report it to the author of the 'stadtreinigung_hamburg' custom integration

**Comment by jugla** [comment]
Thanks for your feed back.
I will perform the enhancement (remove deprecated)

**Comment by jugla** [comment]
Done with version v13.1.0 .
Thanks for your issue :-)
