### ISSUE TITLE
v13.1.0 breaks matplotlib "fix" for x86 and x64 users

### ISSUE THREAD

**Issue by CaptInsano** [jugla/worldtidesinfocustom#30]
The hacky "fix" for missing matplotlib (for x86 and x64 systems) no longer works with version 13.1.0. 

The temporary "fix" I am talking about can be seen here:

https://github.com/jugla/worldtidesinfocustom/issues/26#issuecomment-2039834824

or a persistent "fix" can be achieved by manually editing the manifest.json from v13.0.0 to add the matplotlib requirement as per here:

https://github.com/jugla/worldtidesinfocustom/issues/26#issuecomment-2050353576

Neither of these fixes work with v13.1.0, has matplotlib been removed from the integration completely?

Is there anyway of re-adding the matplotlib functionality for those of use not affected with the matplotlib issues on raspi hardware?

As always, thanks so much for your work on this.

**Comment by jugla** [comment]
Hello,
Matplot is still in the integration, just add in `manifest.json` the matplotlib version you have put : 
`"requirements": ["pyworldtidesinfo==3.0.1"],`
==>
`"requirements": ["pyworldtidesinfo==3.0.1", "matplotlib==xxxx"],`

**Comment by jugla** [comment]
Thanks for the feed back :-)

**Comment by jugla** [comment]
if it not works, please can you give me the homeassistant log, the start up part to see the error message.

**Comment by CaptInsano** [comment]
Sorry for delay, I did not get enough time until now to mess around with this:

User error I think, I had added matplotlib to manifest.json but must have added it incorrectly.

Thanks as always!
