### ISSUE TITLE
Code changes 

### ISSUE THREAD

**Issue by rjenx** [jugla/worldtidesinfocustom#4]
Hi, great project which I have been looking for a tidal solution for ages. Thank you for your efforts. One thing to get the sensors to work I had to make a small change.
The single quotes surrounding '{{ as_timestamp(states.... etc were changed to double quotes as per the rest of the sensors, the double quotes surrounding %a %d/%m.... etc we changed to single quotes. 

`    sensors:
      tide_royan_next_high:
        value_template: "{{ as_timestamp(states.sensor.royan_tides.attributes.high_tide_time_utc) | timestamp_custom('%a %d/%m/%Y %H:%M') }}"
        friendly_name: "Royan Next High Tide"`

Same on the tide_next_low sensor. 

As a side note:
Now the sensors are reporting data, I have another problem to resolve, I am working on why the tidal height is out by a considerable amount from the local prediction. I think its the datum used.

**Comment by jugla** [comment]
Hello,
Thanks a lot  for your comments.

I will check your proposed syntax on my Home Assistant in order to update the "how to".

For your last issue, for explanation on vertical ref, you can see [https://www.sailingissues.com/navcourse7.html](https://www.sailingissues.com/navcourse7.html).
In your case, is it a 'tide' extrapolation or your site is near a tide station ?

**Comment by rjenx** [comment]
Thanks Jugla, I am not a great coder but looking at the python am I correct the datum is LAT? If yes I don't understand the cause of the problem. In the UK we use chart datum which normally is broadly equivalent to the LAT value. So I am unsure how to proceed. 
To give you an example, the sensor for next low tide indicates (negative) -1.261m @ 03:38 tomorrow local. However EasyTide (based on UK Hydrographic Data) shows the low tide to be 1.5m @ 03:13.  The time is ok, but the depth is completely out. At first I thought it was picking up a different datum or different tidal station. 

My lat / long is within 1 km of the Portsmouth UK dockyard which is a primary tidal station, I can't see on the Worldtides site the lat / long for the portsmouth station to confirm its not picking another tidal station. 

Appreciate any insight you can provide.

**Comment by jugla** [comment]
Hereafter my snapshot (watch out my local time is different from yours, since I'm in France)
I've got 1,126 meters for low tide for @03:38 tomorrow local
![image](https://user-images.githubusercontent.com/59493499/109074796-7f060500-76f8-11eb-9e69-42934689e94c.png)

**Comment by rjenx** [comment]
ok thanks Jugla, there is something wrong with my implementation then. I have amended the lat/long to the same as worldtides publishes for Portsmouth Harbour, no change.  In fact the original sensor.portsmouth_tides shows significant less information than your screenshot. 

I have a separate issue which is less important than getting the basic data correct, when I implement the tidal curve code I get an error "Platform error sensor.generic - No module named 'homeassistant.components.generic.sensor'" I am assuming this goes in the sensor block the same as the rest of the code? Do you know what I am missing?
 
![image](https://user-images.githubusercontent.com/64302977/109136181-c370bf80-774f-11eb-8636-3765b18274c5.png)

**Comment by jugla** [comment]
Hello,
Please can you tell me which version do you have for HA and worldtidesinfocustom ?

If you declare "only" the platform you get one sensor with all attributes.
Can you give me the section configuration.yaml relating to the worldtidesinfocustom   (you can hide your key) ?

Thanks in advance
Philippe

**Comment by rjenx** [comment]
Hi Philippe, 
My HA is on 2021.2.0 and I downloaded the hacs version of worldtidesinfocustom, the manifest says v2.1.2

My configuration is set up as packages, Here is the relevant code:

`## Tidal Data for Portsmouth
  - platform: worldtidesinfo
    api_key: !secret wt_api
    name: portsmouth_tides
    latitude: !secret wt_lat
    longitude: !secret wt_long

  - platform: template
    sensors:
      tide_portsmouth_next_high:
        value_template: "{{ as_timestamp(states.sensor.portsmouth_tides.attributes.high_tide_time_utc) | timestamp_custom('%a %d/%m/%Y %H:%M') }}"
        friendly_name: "portsmouth Next High Tide"
      tide_portsmouth_next_low:
        value_template: "{{ as_timestamp(states.sensor.portsmouth_tides.attributes.low_tide_time_utc) | timestamp_custom('%a %d/%m/%Y %H:%M') }}"
        friendly_name: "portsmouth Next Low Tide"
      tide_next_high_height:
        value_template: "{{ state_attr('sensor.portsmouth_tides','high_tide_height')  }}"
        friendly_name: "portsmouth Next High Tide Height"
        unit_of_measurement: m
      tide_portsmouth_next_low_height:
        value_template: "{{ state_attr('sensor.portsmouth_tides','low_tide_height')  }}"
        friendly_name: "portsmouth Next Low Tide Height"
        unit_of_measurement: m
      tide_portsmouth_credit:
        value_template: "{{ state_attr('sensor.portsmouth_tides','CreditCallUsed')  }}"
        friendly_name: "portsmouth Tide Credit"
        unit_of_measurement: credit
      tide_portsmouth_current_height:
        value_template: "{{ state_attr('sensor.portsmouth_tides','current_height')  }}"
        friendly_name: "portsmouth Tide Current Height"
        unit_of_measurement: m
`

**Comment by jugla** [comment]
Hello
I see one mistake . There is a mispelling in configuration
The platform is 
**worldtidesinfocustom**

You have put
**worldtidesinfo**

**Comment by rjenx** [comment]
The missing text, fixed the data issue. Wow, I wonder why it worked without the "custom" . Thank you Philippe for all your help. 

Richard

**Comment by jugla** [comment]
your welcome ;-)
