### ISSUE TITLE
Default distance a bit short

### ISSUE THREAD

**Issue by ioios-io** [jugla/worldtidesinfocustom#5]
Great work,  everything setup nicely except my local station was 13km away and so had to specify. I upped it to 50 and it seems to use the closest and also provide a list of nearby stations. This is really nice extra info, is there any reason to keep it so short?

Thanks for your work,
John

**Comment by jugla** [comment]
Thanks !
10km is the same behaviour as "world tide" info web site.
After a certain distance , it means that tides station has no meaning respect to your lat/long.
==> it depends of your place.

Ok to set up to 50km by default

**Comment by jugla** [comment]
will be close in next release

**Comment by jugla** [comment]
close in V2.2.5
