### ISSUE TITLE
Request: Allow customizing tide plot colors

### ISSUE THREAD

**Issue by ChrisRomp** [jugla/worldtidesinfocustom#6]
The API allows passing of parameters for the `plot` ([ref](https://www.worldtides.info/apidocs)) to customize its colors and other parameters. To make this display nicely on my lovelace dashboard, I'd like to use a darker background color.

I'm not a Python dev (I am a dev), but I'll fork your repo and take a shot at passing the values in as configuration parameters and issue a PR if I can get it working.

I suggest using `plot_color` and `plot_background` as configuration parameter names.

**Comment by jugla** [comment]
Great !
ok for the name `plot_color` and `plot_background`
