### ISSUE TITLE
Sensor not appearing

### ISSUE THREAD

**Issue by wreuvers** [jugla/worldtidesinfocustom#8]
I just cannot get the main Sensor to appear - I am using the exact code recommended
~~
  - platform: worldtidesinfocustom
    name: royan_tides
    api_key: 1c86297b-xxxx-xxxx-xxxx-xxxxxxxxxxx
    latitude: 45.61949378902948
    longitude: -1.0318721687376207
  - platform: template
    sensors:
      tide_royan_next_high:
        value_template: '{{ as_timestamp(states.sensor.royan_tides.attributes.high_tide_time_utc) | timestamp_custom("%a %d/%m/%Y %H:%M") }}'
        friendly_name: "Royan Next High Tide"
      tide_royan_next_low:
        value_template: '{{ as_timestamp(states.sensor.royan_tides.attributes.low_tide_time_utc) | timestamp_custom("%a %d/%m/%Y %H:%M") }}'
        friendly_name: "Royan Next Low Tide"
      tide_royan_next_high_height:
        value_template: "{{ state_attr('sensor.royan_tides','high_tide_height')  }}"
        friendly_name: "Royan Next High Tide Height"
        unit_of_measurement: m
      tide_royan_next_low_height:
        value_template: "{{ state_attr('sensor.royan_tides','low_tide_height')  }}"
        friendly_name: "Royan Next Low Tide Height"
        unit_of_measurement: m
      tide_royan_credit:
        value_template: "{{ state_attr('sensor.royan_tides','CreditCallUsed')  }}"
        friendly_name: "Royan Tide Credit"
        unit_of_measurement: credit
      tide_royan_current_height:
        value_template: "{{ state_attr('sensor.royan_tides','current_height')  }}"
        friendly_name: "Royan Tide Current Height"
        unit_of_measurement: m
      tide_royan_station:
        value_template: "{{ state_attr('sensor.royan_tides','tidal_station_used')  }}"
        friendly_name: "Royan Tide Station used"
~~

I see the calls being made to the api
![image](https://user-images.githubusercontent.com/80078939/113233212-b3775e80-926c-11eb-953e-ee78d430bbde.png)

And this is all I see in the States
![image](https://user-images.githubusercontent.com/80078939/113233275-da359500-926c-11eb-9765-5698e6a1e44c.png)

**Comment by jugla** [comment]
Thanks to have created the issue.
Please can you give me : 
- your hardware
- your OS
- the version of HA
- the version of  worldtidesinfocustom

Please can you give your log ?

**Comment by jugla** [comment]
Please can you check if the directory `your_configuration_directory/www` exists.
If not, then you can create it.
On linux , within your HA account, in  `your_configuration_directory` : 
`mkdir www`
Thanks in advance

**Comment by wreuvers** [comment]
Hi Jugla
That worked - I created the directory called www and now I see the sensors and the image!!! Thanks - I really appreciate your hard work!!!!

**Comment by jugla** [comment]
Thanks a lot for your feed back.
I prepare a release in order to create directory, if it does not exist

**Comment by jugla** [comment]
The release V2.5.2 is created to force the www directory creation
